pluto_planner:
  _target_: src.planners.carplan_planner.CarPLANPlanner
  _convert_: "all"

  render: false
  eval_dt: 0.1
  eval_num_frames: 40
  candidate_subsample_ratio: 1.0
  candidate_min_num: 10
  learning_based_score_weight: 0.3
  postprocessing: False

  planner:
    ${model}

  planner_ckpt:
