_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
  - behind_long_vehicle
  - changing_lane
  - following_lane_with_lead
  - high_lateral_acceleration
  - high_magnitude_speed
  - low_magnitude_speed
  - near_multiple_vehicles
  - starting_left_turn
  - starting_right_turn
  - starting_straight_traffic_light_intersection_traversal
  - stationary_in_traffic
  - stopping_with_lead
  - traversing_pickup_dropoff
  - waiting_for_pedestrian_to_cross
scenario_tokens:
  - "0a1adb702c0f5949"
  - "003445cf99235331"
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: 15
ego_displacement_minimum_m: null
ego_start_speed_threshold: null
ego_stop_speed_threshold: null
speed_noise_tolerance: null
expand_scenarios: null
remove_invalid_goals: true
shuffle: false
